### ISSUE TITLE
Type Error Received when running bot

### ISSUE THREAD

**Issue by w0ntonsoup** [amarvin/fantasy-football-bot#30]
Here's the entire log:

```
python3 demo.py                                                                                                                                                  1 ↵  3086  09:56:03
Retrying projections for pid 100030
Retrying projections for pid 100030
Retrying projections for pid 100030
Retrying projections for pid 100030
Retrying projections for pid 30538
Retrying projections for pid 30538
Retrying projections for pid 30538
Retrying projections for pid 30538
Retrying projections for pid 28188
Retrying projections for pid 28188
Retrying projections for pid 28188
Retrying projections for pid 28188
Retrying projections for pid 29274
Retrying projections for pid 29274
Retrying projections for pid 29274
Retrying projections for pid 29274
Retrying projections for pid 30157
Retrying projections for pid 30157
Retrying projections for pid 30157
Retrying projections for pid 30157
Retrying projections for pid 23997
Retrying projections for pid 23997
Retrying projections for pid 23997
Retrying projections for pid 23997
Total runtime: 0:26:16.402187
Traceback (most recent call last):
  File "demo.py", line 19, in <module>
    ffbot.optimize(df, week, team)
  File "/Users/c60708a/Code/misc/fantasy-football-bot/ffbot/optimizer.py", line 50, in optimize
    FreeAgent[p] = True if np.isnan(row['Owner ID']) and owner == 'Free Agent' else False
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''```

**Comment by amarvin** [comment]
Thanks for reporting that and sorry the bug happened. I will implement a fix by switching from `np.isnan` to `pd.isnull` to avoid this error (https://stackoverflow.com/a/36001191/6068036).

**Comment by w0ntonsoup** [comment]
Thanks for your hard work. Love the bot.

**Comment by amarvin** [comment]
Hmm, my fix is inconsistent. I'll try more things later.
